#
# Copyright 2014-2016 CyberVision, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: '2'
services:
  sql:
    image: mariadb:5.5
    networks:
      - back-tier
    volumes:
      - ./docker-data/sql:/var/lib/mysql
    env_file: mariadb.env

  zookeeper:
    image: jplock/zookeeper:3.4.10
    networks:
      - back-tier
    volumes:
      - ./docker-data/zookeeper:/tmp/zookeeper

  nosql:
    image: mongo:3.2
    networks:
      - back-tier
    volumes:
      - ./docker-data/nosql:/data/db

  kaa_0:
    image: cburr25/kaa:0.10.1
    env_file: kaa.env
    environment:
      - SQL_PROVIDER_NAME=mariadb
      - NOSQL_PROVIDER_NAME=mongodb
      - SERVICES_WAIT_TIMEOUT=-1 # Wait forever for Zookeeper and SQL
      - ADMIN_PORT=8080
      - BOOTSTRAP_TCP=10088
      - BOOTSTRAP_HTTP=10089
      - OPERATIONS_TCP=10097
      - OPERATIONS_HTTP=10099
    depends_on:
      - sql
      - nosql
      - zookeeper
      - smtp
    networks:
      - back-tier
      - front-tier
    ports:
      - "8080:8080"
      - "10088:10088"
      - "10089:10089"
      - "10097:10097"
      - "10099:10099"

  smtp:
    image: jeanberu/mailcatcher
    ports:
      - 1025:1025 # SMTP
      - 1080:1080 # Web interface 
    networks:
      - back-tier   

networks:
  back-tier:
    driver: bridge
  front-tier:
    driver: bridge
# volumes:
#   sql-data:
#   nosql-data:
#   zookeeper-data:
